"""Changed Gemstone-User relationship settings

Revision ID: 23757e502e08
Revises: 545c5ec2ce08
Create Date: 2024-09-13 02:48:18.732865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23757e502e08'
down_revision = '545c5ec2ce08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gemstones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gemstones_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gemstones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_gemstones_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
