"""Initial migration

Revision ID: 2a85163709bc
Revises: 
Create Date: 2024-09-13 02:28:27.147490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a85163709bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gemstones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gemstone_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=55), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gemstones_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gemstone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gemstone_id'], ['gemstones.id'], name=op.f('fk_reviews_gemstone_id_gemstones')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_gemstones',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('gemstones_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gemstones_id'], ['gemstones.id'], name=op.f('fk_user_gemstones_gemstones_id_gemstones')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_user_gemstones_users_id_users')),
    sa.PrimaryKeyConstraint('users_id', 'gemstones_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_gemstones')
    op.drop_table('reviews')
    op.drop_table('gemstones')
    op.drop_table('users')
    # ### end Alembic commands ###
